const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),js=html.match(/<script>([\s\S]*)<\/script>/)[1];
const gradient={addColorStop(){}},draws=[];
const ctx=new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,drawImage(img,...a){if(a.length===8){const [x,y,w,h]=a;assert(x>=0&&y>=0&&w>0&&h>0&&x+w<=img.naturalWidth+.01&&y+h<=img.naturalHeight+.01,'sprite crop bounds');}draws.push(a);}}, {get:(o,k)=>k in o?o[k]:()=>{}});
const elements={},handlers={},storage=new Map();const element=id=>elements[id]||(elements[id]={hidden:false,innerHTML:'',getContext:()=>ctx,addEventListener(){},setAttribute(){},focus(){},querySelectorAll:()=>[],insertAdjacentElement(){}});
class AssetImage{set src(value){const b=Buffer.from(value.split(',')[1],'base64');this.naturalWidth=b.readUInt32BE(16);this.naturalHeight=b.readUInt32BE(20);this.complete=true;}}
const sandbox={console,Math,Set,Image:AssetImage,localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null},navigator:{getGamepads:()=>[]},document:{createElement:()=>element('new'),getElementById:element,addEventListener:(type,fn)=>handlers[type]=fn,querySelectorAll:()=>[],querySelector:element},window:{addEventListener(){}},requestAnimationFrame(){}};
vm.createContext(sandbox);vm.runInContext(js,sandbox);const run=code=>vm.runInContext(code,sandbox);
run(`function check(ok,msg){if(!ok)throw Error(msg)} function tick(n){for(let i=0;i<n;i++){update(1/120);for(const k in pressed)delete pressed[k];}} function atObject(o){p.x=o.x-11;p.y=o.y-p.h;p.on=true;mode='play';interact();} function noEnemies(){for(const r of rooms)r.enemies=[];}`);
run(`reset();check(rooms[0].width>=21000&&rooms[1].width>=22000,'expanded areas');check(rooms[0].enemies.length>=45&&rooms[1].enemies.length>=42,'encounters');check(rooms[0].gates.length===4&&rooms[1].gates.length===4,'four progression seals per area');check(new Set(rooms[0].enemies.map(e=>e.type)).size===5,'five enemy roles');
noEnemies();keys.KeyD=true;tick(60);delete keys.KeyD;check(p.x>200,'movement');pressed.Space=true;tick(1);check(p.vy<0,'jump');tick(130);check(p.on,'landing');
reset();const victim=enemy(150);victim.cd=99;rooms[0].enemies=[victim];p.dir=1;startAction();updateAction(.1);check(victim.hp===50,'no damage in windup');updateAction(.1);check(victim.hp===25,'damage in sword contact frame');updateAction(.08);check(victim.hp===25,'one hit per animation');updateAction(.3);check(!p.action,'recovery ends');
p.cd=0;p.mana=100;victim.hp=100;startAction(true);check(p.mana===65&&shots.length===0,'special is costly close-range sword attack');updateAction(.24);check(victim.hp===68,'special damage');check(!startAction(true),'no special spam');
p.action=null;p.cd=0;victim.x=400;victim.hp=50;p.mana=100;p.specialCd=0;startAction(true);updateAction(.3);check(victim.hp===50,'special cannot hit across room');
reset();noEnemies();keys.KeyK=true;tick(1);check(p.parry>0&&p.block,'guard edge opens parry');const attacker=enemy(150);check(hurt(20,150,false,attacker)==='parry'&&p.hp===100&&attacker.stun>1,'frontal parry stuns');check(p.riposte===2,'riposte reward');tick(40);p.inv=0;check(hurt(20,150)==='block'&&p.stamina<100,'held shield is not repeated parry');p.inv=0;p.parry=.15;check(hurt(20,0)==='hit','rear attack is not parried');p.inv=0;p.parry=.15;check(hurt(20,150,true)==='hit','unblockable attack');
reset();noEnemies();keys.KeyK=true;tick(1);shots.push({x:p.x+36,y:p.y+20,vx:-200,vy:0,life:2,damage:20});tick(1);check(shots[0].friendly&&shots[0].vx>0,'projectile reflection');
reset();const hound=enemy(240,GROUND,'hound');rooms[0].enemies=[hound];hound.cd=0;updateEnemies(.01);check(hound.wind>0&&hound.dir===-1,'dog faces player');p.x=330;updateEnemies(.2);check(hound.dir===-1,'dog locks windup direction');updateEnemies(.5);check(hound.dash>0,'dog uses jump attack');const oldX=hound.x;updateEnemies(.04);check(hound.x<oldX,'dog attacks locked direction');
`);console.log('PASS movement, larger campaign, timed sword impacts, special balance, parry/block/rear/unblockable/reflection, dog direction.');
run(`reset();const e=rooms[0].enemies[0];hit(e,1000);check(orbs.length===1&&souls===0,'kill spawns collectible soul');hit(e,1000);check(orbs.length===1,'no duplicate reward');p.x=orbs[0].x-11;p.y=orbs[0].y-22;updateOrbs(.01);check(souls===7&&orbs.length===0,'pickup grants currency');check(!upgrade('damage')&&damageLevel===0&&souls===7,'insufficient funds atomic');souls=100;check(upgrade('damage')&&souls===70&&damageLevel===1,'damage purchase');check(upgrade('armor')&&souls===45&&armorLevel===1,'armor purchase');p.inv=0;p.block=false;p.hp=100;hurt(100,150);check(p.hp===8,'armor reduces damage 8 percent');
reset();noEnemies();const gate=rooms[0].gates[0];p.x=gate.x-40;keys.KeyD=true;tick(20);delete keys.KeyD;check(p.x+p.w<=gate.x-10,'closed gate collision');const bells=rooms[0].objects.filter(o=>o.kind==='bell');atObject(bells[0]);check(!flags.bells&&bellSequence.length===0,'wrong sequence resets');for(const i of [1,0,2])atObject(bells[i]);check(flags.bells,'bell puzzle');p.x=gate.x-40;keys.KeyD=true;tick(30);delete keys.KeyD;check(p.x>gate.x,'open gate traversable');
for(const o of rooms[0].objects.filter(o=>o.kind==='vow'))atObject(o);check(flags.vows,'three vows collected');const crate=rooms[0].objects.find(o=>o.kind==='crate');p.x=crate.x-45;p.y=407;keys.KeyD=true;tick(410);delete keys.KeyD;check(flags.weight&&Math.abs(crate.x-11900)<25,'push crate completes pressure plate');
for(const o of rooms[0].objects.filter(o=>o.kind==='seal'))atObject(o);check(flags.wardens,'guardian seal interaction');p.x=rooms[0].door;interact();check(stage===0,'vigils required at exit');for(const trial of rooms[0].objects.filter(o=>o.kind==='trial')){p.x=trial.x;trial.active=true;for(let wave=0;wave<3;wave++){updateTrials(2);check(rooms[0].enemies.some(e=>e.trial===trial.id&&e.hp>0),'vigil spawns wave');for(const e of rooms[0].enemies.filter(e=>e.trial===trial.id))hit(e,1000);}updateTrials(2);check(trial.cleared,'vigil completes after three waves');}p.x=rooms[0].door;interact();check(stage===1,'first area exit');const mirrors=rooms[1].objects.filter(o=>o.kind==='mirror');atObject(mirrors[0]);atObject(mirrors[2]);atObject(mirrors[2]);check(flags.mirrors,'mirror puzzle');atObject(rooms[1].objects.find(o=>o.kind==='echo'));check(p.double,'double jump unlock');for(const o of rooms[1].objects.filter(o=>o.kind==='shard'))atObject(o);check(flags.echoes,'echo fragments');atObject(rooms[1].objects.find(o=>o.kind==='lever'));check(clockLeft===18,'timed lever');atObject(rooms[1].objects.find(o=>o.kind==='clockSeal'));check(flags.clock&&clockLeft===0,'permanent clock shortcut');for(const o of rooms[1].objects.filter(o=>o.kind==='flame').reverse())atObject(o);check(flags.flames,'reverse flame sequence');
souls=75;damageLevel=2;armorLevel=1;checkpoint={stage:1,x:7240};litAltars.add('1-altar-7240');saveGame();reset();check(loadGame()&&stage===1&&p.x===7240&&souls===75&&damageLevel===2&&armorLevel===1&&p.double&&flags.flames,'save restores progression');p.hp=0;respawn();check(souls===75&&flags.flames,'death preserves currency and progression');
`);console.log('PASS souls and atomic upgrades, armor, gates, all eight puzzle chains, travel, save/load and death persistence.');
run(`reset();travel(2,520);check(mode==='intro'&&boss.max===700,'boss intro and increased life');const introHP=p.hp;tick(50);check(p.hp===introHP,'intro safe');pause();const it=introTime;tick(40);check(introTime===it,'pause freezes cinematic');pause();finishIntro();
boss.hp=350;updateBoss(.01);check(boss.phase===2&&boss.enrage>2,'phase two transformation');hit(boss,99);check(boss.hp===350,'transformation protected');boss.enrage=0;boss.stun=0;boss.wind=0;boss.swing=0;boss.cd=0;boss.cycles=0;updateBoss(.01);check(boss.kind===6&&boss.wind>=1.5&&boss.flood===0,'flood warning before damage');updateBoss(1.7);updateBoss(.2);check(boss.flood>3,'flood starts with animation');p.y=407;p.inv=0;const hp=p.hp;updateBoss(.01);check(p.hp<hp,'flood hurts floor');p.y=355-p.h;p.inv=0;const safeHP=p.hp;updateBoss(.1);check(p.hp===safeHP,'platform evades flood');
const bell=rooms[2].objects[0];atObject(bell);check(boss.stun>1&&boss.flood===0&&bell.cooldown===24,'arena bell interrupts');const bHP=boss.hp;atObject(bell);check(boss.hp===bHP,'bell cooldown');
for(let kind=0;kind<8;kind++){boss.stun=0;boss.kind=kind;boss.wind=.01;boss.windMax=1;boss.swing=0;boss.enrage=0;boss.dash=0;boss.flood=0;boss.breath=0;boss.attackClock=0;boss.emitted=false;boss.target=600;updateBoss(.02);updateBoss(.2);assetBoss(boss);}check(pillars.length>0,'arena-targeting attacks');
for(const [name,a]of Object.entries(art)){check(a.img.naturalWidth%a.frames===0,'integral frames '+name);for(let frame=0;frame<a.frames;frame++)sprite(name,100,455,1,frame);}
reset();for(const s of [0,1,2]){stage=s;if(s===2)makeBoss();for(const x of [100,3550,7300,11200,15000,18000]){if(x>rooms[s].width)continue;p.x=x;cam=Math.max(0,x-300);render();}}
`);console.log('PASS boss cinematic, phase transition, new attacks, platform safety, arena bells, all sprite bounds and campaign rendering.');
// Reachability graph for the actual jump arc and one-way platforms. Every quest
// collectible must have a reachable supporting platform, not merely exist in data.
run(`reset();for(let s=0;s<2;s++){stage=s;const r=rooms[s],nodes=[platform(0,GROUND,r.width),...r.platforms],reachable=new Set([0]);for(let iteration=0;iteration<nodes.length;iteration++)for(let i=0;i<nodes.length;i++)if(reachable.has(i))for(let j=1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],rise=a.y-b.y,maxRise=s===1?225:116;const horizontal=Math.max(0,b.x-(a.x+a.w),(a.x)-(b.x+b.w));if(rise>=0&&rise<=maxRise&&horizontal<=(s===1?270:140))reachable.add(j);}
for(const o of r.objects.filter(o=>['vow','shard','echo','cache'].includes(o.kind))){check(nodes.some((f,i)=>reachable.has(i)&&o.x>f.x-30&&o.x<f.x+f.w+30&&Math.abs(f.y-o.y)<65),'reachable quest item '+o.id);}}
`);console.log('PASS vertical quest-item reachability for both areas.');
run(`reset();travel(1,5610);noEnemies();p.double=false;for(const [x,y]of [[5610,373],[5760,291],[5890,209]]){p.x=x;p.on=true;pressed.Space=true;tick(1);tick(115);check(p.on&&Math.abs(p.y+p.h-y)<1,'actual jump arc reaches echo stair '+y);}keys.KeyD=true;tick(70);delete keys.KeyD;pressed.KeyE=true;tick(1);check(p.double,'echo acquired with real jump physics before double jump');
const timerGate=rooms[1].gates.find(g=>g.key==='clock');p.x=timerGate.x+50;p.y=407;clockLeft=.01;tick(3);check(p.x===12400&&!flags.clock,'failed timer returns to lever without trapping player');
reset();const guardianSeal=rooms[0].objects.find(o=>o.kind==='seal');atObject(guardianSeal);check(!guardianSeal.taken,'living guardian protects seal');const vigil=rooms[0].objects.find(o=>o.kind==='trial');vigil.cleared=true;saveGame();reset();loadGame();check(rooms[0].objects.find(o=>o.id===vigil.id).cleared,'completed vigil persists');
p.on=false;p.mana=100;check(!startAction(true)&&p.mana===100,'grounded special prevents crouching in midair');
`);console.log('PASS actual relic jump sequence, timer recovery, living guardian lock, persistent vigils and grounded special.');
module.exports={sandbox,run};
