const {sandbox,run}=require('./campaign.test.cjs');
let pads=[];sandbox.navigator={getGamepads:()=>pads};const pad={index:0,connected:true,mapping:'standard',id:'Simulated standard DualShock 4',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};
pads=[pad];run("reset();pollGamepad();check(padId===0,'controller connection')");
pad.axes[0]=.15;run("pollGamepad();check(padAxis===0,'deadzone')");pad.axes[0]=.6;run("pollGamepad();check(Math.abs(padAxis-.5)<.001,'analog movement')");
pad.axes[0]=0;pad.buttons[0].pressed=true;run("pollGamepad();check(pressed.Space,'cross jump');update(1/120);delete pressed.Space;pollGamepad();check(!pressed.Space,'no repeat edge')");
pad.buttons[0].pressed=false;pad.buttons[2].pressed=true;pad.buttons[3].pressed=true;pad.buttons[1].pressed=true;pad.buttons[4].pressed=true;run("pollGamepad();check(pressed.KeyJ&&pressed.KeyL&&pressed.KeyE&&held('KeyK'),'combat mapping')");
pad.buttons.forEach(b=>b.pressed=false);pad.buttons[9].pressed=true;run("pollGamepad();check(mode==='pause','options pause')");pad.buttons[9].pressed=false;run('pollGamepad()');pad.buttons[0].pressed=true;run("pollGamepad();check(mode==='play','cross resumes')");
pad.buttons.forEach(b=>b.pressed=false);run('pollGamepad()');pad.buttons[8].pressed=true;run("pollGamepad();check(mode==='journal','Share opens journal')");pad.buttons[8].pressed=false;pad.buttons[1].pressed=true;run("pollGamepad();check(mode==='play','circle closes journal')");
pad.buttons[1].pressed=false;pad.buttons[4].pressed=true;run('pollGamepad()');pads=[];run("keys.KeyD=true;pollGamepad();check(mode==='pause'&&!held('KeyK')&&padAxis===0&&!keys.KeyD,'disconnect clears controls')");
const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(){},cancelScheduledValues(){}});let starts=0;
class MockAudio{constructor(){this.currentTime=0;this.sampleRate=100;this.state='running';this.destination={}}createGain(){return{gain:param(),connect(){},disconnect(){}}}createOscillator(){return{frequency:param(),connect(){},disconnect(){},start(){starts++},stop(){}}}createConvolver(){return{connect(){}}}createBuffer(c,n){return{getChannelData:()=>new Float32Array(n)}}createBufferSource(){return{connect(){},disconnect(){},start(){starts++},stop(){}}}createBiquadFilter(){return{frequency:param(),connect(){},disconnect(){}}}resume(){return Promise.resolve()}}
sandbox.window.AudioContext=MockAudio;run("reset();enableAudio();scheduleMusic();travel(2,120);finishIntro();scheduleMusic();boss.phase=2;scheduleMusic();for(const sound of ['swipe','hit','block','death','slam','cast','roar','step'])sfx(sound);check(musicTheme==='rage','phase-two score');pause();scheduleMusic();check(musicTheme==='silent','pause mutes score')");if(starts<30)throw Error('audio synthesis missing');
console.log('PASS DualShock standard mapping, Share journal, disconnect safety, combat SFX and phase-two soundtrack.');
